// Generated by goversion v0.1.0-SNAPSHOT
package goversion

// The following variables should be filled with goversion ldflags
var (
	buildBy      string
	buildDate    string
	buildArch    string
	buildOS      string
	gitCommit    string
	gitTreeState string
	goVersion    string
	version      string
)

func init() {
	Set(Info{
		BuildBy:      buildBy,
		BuildDate:    buildDate,
		BuildArch:    buildArch,
		BuildOS:      buildOS,
		GitCommit:    gitCommit,
		GitTreeState: gitTreeState,
		GoVersion:    goVersion,
		Version:      version,
	})
}
