package cmd

import (
	"context"
	"errors"
	"io"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"github.com/erwinvaneyk/cobras"
	"github.com/spf13/cobra"

	"github.com/erwinvaneyk/goversion"
)

type GenerateOptions struct {
	DisableInit              bool
	GeneratedFilePath        string
	GoVersionPackage         string
	GeneratedFilePackageName string
	GoversionVersion         string
}

func NewCmdGenerate() *cobra.Command {
	opts := &GenerateOptions{
		GoVersionPackage:         goversion.PackageName,
		GeneratedFilePath:        "",
		GeneratedFilePackageName: "main",
		GoversionVersion:         goversion.Get().Version,
	}

	cmd := &cobra.Command{
		Use: "generate",
		Short: "",
		Run: cobras.Run(opts),
	}

	cmd.Flags().StringVarP(&opts.GeneratedFilePath, "output", "o", opts.GeneratedFilePath, "Where to write the generated version file to. If none or '-' is provided, it will be written to stdout.")
	cmd.Flags().StringVarP(&opts.GeneratedFilePackageName, "pkg", "p", opts.GeneratedFilePackageName, "The package name of the generated file.")
	cmd.Flags().StringVar(&opts.GoVersionPackage, "goversion", opts.GoVersionPackage, "The package path to use to import the goversion API.")
	cmd.Flags().BoolVar(&opts.DisableInit, "disable-init", opts.DisableInit, "If set, the init function is not generated.")
	return cmd
}

func (o *GenerateOptions) Complete(cmd *cobra.Command, args []string) error {
	return nil
}

func (o *GenerateOptions) Validate() error {
	if o.GeneratedFilePackageName == "" {
		return errors.New("a package name (--pkg, -p) is required")
	}
	return nil
}

func (o *GenerateOptions) Run(ctx context.Context) error {
	var writesToFile bool
	var writer io.Writer
	if o.GeneratedFilePath == "" || o.GeneratedFilePath == "-" {
		writer = os.Stdout
	} else {
		fd, err := os.Create(o.GeneratedFilePath)
		if err != nil {
			return err
		}
		writer = fd
		writesToFile = true
		defer fd.Close()
	}

	err := versionFieldsTemplate.Execute(writer, o)
	if err != nil {
		return err
	}

	if writesToFile {
		absGeneratedFilePath, err := filepath.Abs(o.GeneratedFilePath)
		if err != nil {
			absGeneratedFilePath = o.GeneratedFilePath
		}
		log.Printf("Generated goversion-fields file: '%s'", absGeneratedFilePath)
	}

	return nil
}

var versionFieldsTemplate = template.Must(template.New("version.gen.go").Parse(`// Generated by goversion {{.GoversionVersion}}
package {{.GeneratedFilePackageName}}
{{ if .GoVersionPackage}}
import goversion "{{.GoVersionPackage}}"
{{end}}
// The following variables should be filled with goversion ldflags
var (
	buildBy      string
	buildDate    string
	buildArch    string
	buildOS      string
	gitCommit    string
	gitTreeState string
	goVersion    string
	version      string
)

{{if not .DisableInit}}func init() {
	{{ if .GoVersionPackage}}goversion.{{end}}Set({{ if .GoVersionPackage}}goversion.{{end}}Info{
		BuildBy:      buildBy,
		BuildDate:    buildDate,
		BuildArch:    buildArch,
		BuildOS:      buildOS,
		GitCommit:    gitCommit,
		GitTreeState: gitTreeState,
		GoVersion:    goVersion,
		Version:      version,
	})
}
{{end}}`))
